# Site settings
title: "Long Streets Montana"
email: "hello@longstreetsmt.com"
description: Exploring Montana's economic future
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://longstreetsmt.com" # the base hostname & protocol for your site

twitter_username: "longstreetsmt"
facebook_page:

# Build settings
markdown: kramdown
